### ISSUE TITLE
Exception thrown when using on internal project using ArrayOfMessage[]

### ISSUE THREAD

**Issue by joostvanmeeuwen** [DannyvdSluijs/WsdlToClass#4]
Console output:
  [Exception]  
  Unable to parse input [Message ArrayOfMessage[]] 

Command:
./wsdltoclass wsdltoclass:import -o /tmp --namespace PersonalWebsiteSoapClient\Soap http://[url here}/index.php/soap/wsdl/

**Comment by DannyvdSluijs** [comment]
Resolved in https://github.com/DannyvdSluijs/WsdlToClass/commit/08e793fdd4924c36f667c65938c498fd3b10a0b9
